project:
  type: website
  output-dir: docs

website:
  favicon: logo.jpg
  title: "Research and Data Incubator"
  navbar:
    logo: logo.jpg
    right:
      - href: index.qmd
        text: Home
      - href: customers.qmd
        text: Our Customers
      - href: contact.qmd
        text: Contact us!

format:
  html:
    theme: journal
    css: styles.css
    toc: True
    highlight-style: tango

